### ISSUE TITLE
functions sd and diff spit errors

### ISSUE THREAD

**Issue by thejonrick** [StructuredDataLLC/Basic-Excel-R-Toolkit#3]
Tried 3 very simple functions: mean, sd, and diff. All of which I coded identical to SUM in your code, <i>mutatis mutandis</I>. I used a vertical column in excel of prices. Mean worked with no issue but with both sd and diff, I got a #VALUE error. 

When attempt the converse and read the data into the console first using get.range, again SUM and MEAN worked without issue, but sd and mean result in "Error: stack usage xxxxxx is too close to the limit". 

I am unfamiliar with this error and do not see why it would register. When I try typeof(matrix) is confirms that the vars is in fact "double", and I even tried to convert the matrix into a dataframe and only considering the first column of the matrix to no avail. Any assistance would be appreciated. 

Using Win7, Excel 2010 (32-bit), BERT 0.40

**Comment by duncanwerner** [comment]
At the risk of being very unhelpful, it works for me.  

Before I dig into this, there's something that is not mentioned in the docs but which might be an issue here.  You'll note that for the junk SUM function, the name is all caps.  That's important because otherwise it would recurse indefinitely.  Do me a favor and tell me that you are not calling your sd function "sd", and so on (and if so, try another name or try all caps).

That stack warning sounds like very deep recursion.  If this is the case, try `rm(sd)` to remove the local definition and then try it in the console again.

**Comment by thejonrick** [comment]
I did notice the suse of caps and fixed it as I thought that might have been the cause of the error. However, it did not occur to me that I would have to rm the variable that might have accidentally been created before I realized the caps (I figured I excel restart would refresh...guess not). Looks like it work now!

Thanks!
