### ISSUE TITLE
r console not working at Excel 2010 but working at Excel 2013

### ISSUE THREAD

**Issue by wck01** [StructuredDataLLC/Basic-Excel-R-Toolkit#4]
I have installed version 0.41 and tested it for 4 computers with Excel 2013 (both 32 and 64 bit) and Excel 2010 (both 32 and 64 bit). I found that the r console didn't work at Excel 2010 but worked perfectly at Excel 2013.

Besides, I found that the VBA worked at both Excel 2010 and Excel 2013 such as 
  -    Application.Run "BERT.Exec", "Set.Range('F2:F9', seq(1,10))"

I feel BERT is very great. I prefer BERT much more than RExcel. This is very bad if I can't use r console at my office which use Excel 2010. Is there any help for this? Thanks.

**Comment by duncanwerner** [comment]
I'll set up a test environment to see if I can reproduce the problem.  Can you tell me what version of Windows you are using with Excel 2010?

**Comment by wck01** [comment]
Really appreciated if you can test. I have test it in Windows 7. Both 32 bit and 64 bit didn't work at Excel 2010.

**Comment by duncanwerner** [comment]
It definitely works for me in a clean (VM) install of win 7, excel 2010.  So there must be something different with your environment.  If I build version which does some logging, would you be able to test it?

**Comment by wck01** [comment]
yes，i would liie to test.
2015年9月25日 上午12:45 於 "duncanwerner" <notifications@github.com> 寫道：

**Comment by duncanwerner** [comment]
Here's an instrumented build: [0.43T](http://bert-toolkit.com/files/BERT-Install-0.43T.msi)

When you start Excel, it may pop up a dialog (if there's a problem).  That might be hidden behind the Excel logo, so if it takes a long time to start try alt-tab to find the dialog.

If it starts OK, have a look at the console and try an R command like `ls()`.  Let me know what happens.

**Comment by wck01** [comment]
I have installed 0.43T in Windows 7 (32bit) and Excel 2010 (32bit). After I type ls(), the r console show below and can't show the R objects:

> ls()
BERTCOM.cpp:77 p 0x7349118, 0x73443fc
BERTCOM.cpp:165 p 0x0, hr 0x0
Console.cpp:563 Done:	1244794
BERTCOM.cpp:77 p 0x7349118, 0x734448c
BERTCOM.cpp:165 p 0x0, hr 0x0
BERTCOM.cpp:77 p 0x7349118, 0x7344444
BERTCOM.cpp:165 p 0x0, hr 0x0

![temp](https://cloud.githubusercontent.com/assets/14733122/10090783/f5ffcbca-6365-11e5-97fd-20f9ee6d8aa1.jpg)

**Comment by duncanwerner** [comment]
Thanks for testing that.  That is very helpful, and completely different than what I expected.  I think I might have an idea what's causing the problem, though.

Can you tell me the version string from your Excel 2010?  This is in File tab -> Help under "About Microsoft Excel".  Mine is 14.0.6023.1000 (32-bit).

**Comment by wck01** [comment]
My Excel 2010 string is : 14.0.7153.5000 (32-bit)

**Comment by duncanwerner** [comment]
Here is an update with a possible fix: [0.44T](http://bert-toolkit.com/files/BERT-Install-0.44T.msi)

It also has the debug tracing in it, let me know if you have a chance to try it.

**Comment by wck01** [comment]
I just tried. However, it didn't work and show below:

Basic Excel R Toolkit (BERT) v 0.44
Copyright (C) 2014-2015 Structured Data, LLC

Read startup file OK @ 09/25/15 23:13:43
BERTCOM.cpp:81 p 0x66e9250, 0x0
BERTCOM.cpp:174 p 0x0, hr 0x80030002
BERTCOM.cpp:81 p 0x66e9250, 0x0
BERTCOM.cpp:174 p 0x0, hr 0x80030002
Console.cpp:602 PC
Console.cpp:671 Exec
> ls()
BERTCOM.cpp:81 p 0x66e9250, 0x0
BERTCOM.cpp:174 p 0x0, hr 0x80030002
Console.cpp:563 Done:	368973
>

**Comment by duncanwerner** [comment]
Last try: [0.45T](http://bert-toolkit.com/files/BERT-Install-0.45T.msi)

I'm pretty sure we know what's wrong.  It's something to do with your Excel installation, and probably some missing registry entries.  However we think we can work around it.  I can explain in detail, if you like, but this version _should_ get it working.  Hopefully.

**Comment by wck01** [comment]
Wow. It works finally. I'm very interesting what I miss in registry entries. Besides, I hope you can release a new version without the debug information when you have time.

I use R and Excel in my work everyday. This is very amazing to combine them into one platform. BERT is the great tool I'm looking for. I'm very appreciated your help and creating this tool. This is not enough to simply say a "Thank You". I'm very impressed. Thanks.

**Comment by wck01** [comment]
One more thing. For version 0.45T, I got the error for Set.Range
 - Error in Set.Range("B2:E9", seq(1, 10)) : attempt to apply non-function
I think this was fixed for 0.41. After I copy the startup files from 0.41, it solved.

**Comment by duncanwerner** [comment]
Great, thanks for your help with the testing.  I will get a new build ready in the next few hours.  I think there were some old files in my test branch, so I will make sure everything is clean for the build.

**Comment by duncanwerner** [comment]
Regarding registry entries, I will explain what I think was happening.  I don't know your software background, so if any of this is unclear let me know.

There are two ways to talk to Excel.  There is a C API, which is fast, and there is windows COM, which is slow.  In order to get reasonable performance we use the C API.  However when you are using the console, it runs in a separate thread, and from there we need to use COM to talk to Excel from a different thread.  (R still talks to Excel via C -- COM is just necessary to get in the correct thread context).

COM depends on the registry.  When we use a type library, it looks up the library by the type ID.  Older versions of BERT were using the Excel type library to make these COM calls.  This worked for me, and it worked for you on your Excel 2013 machines, but on your Excel 2010 machine it wasn't working.  In the debug information, the Excel pointer was not being cast correctly and the error 0x80030002 usually means the type information was not found.  

From what I found on the web, it seems like this happens when there is a problem with the Excel installation -- either Excel is upgraded from an old version, or you install a newer version and then remove it.  It's probably not that important because the way we were using it was kind of unusual.  For most things, if you run within Excel you stay on the main thread, and then this won't be a problem.

We fixed it by removing the type library entirely, and using a Dispatch interface -- this is another way to use COM that doesn't require it to find the library.  

If you want to know for sure if this is the case, you could test it with Process Monitor.

**Comment by duncanwerner** [comment]
Closed with release 0.48.

**Comment by wck01** [comment]
I install the latest release 0.48. It works perfectly in Excel 2010.

I'm very appreciated your explanations. I understand why VBA worked while console didn't work. I can feel the power of C API instead of COM. The speed is fast.

I'm so happy you finally fix it by dispatch interface. It's very new for me. I learn a lot from your tool.

I tried different tools for R with VBA. BERT is the best. This will totally change my work practice in future. Thanks.
